### ISSUE TITLE
Need to update the state's values for the theme variables

### ISSUE THREAD

**Issue by nvinogradova** [pace-running/pace3#98] opened 2023-06-21 08:29 UTC
After changing the theme the user needs to refresh the browser tab to see updates. If the user does not refresh the browser, the old settings are displayed.

**Comment by nvinogradova** [comment] 2023-06-21 08:41
To do:
we have to call initTheme after updateTheme has finished. initTheme will update the state's values for the theme variables

**Comment by qutax** [comment] 2023-06-22 14:42
Duplicate of #96

**Closed as completed by qutax** 2023-06-22 14:42 UTC
Labels: Bug
